# Generated by Django 4.0.1 on 2022-01-23 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('By', models.CharField(default=None, max_length=50)),
                ('title', models.CharField(default=None, max_length=255)),
            ],
        ),
    ]
